"""
twinScientist CLI Entry Point

Usage:
    python -m main                          # Interactive mode
    python -m main --question "问题"          # CLI mode
    python -m main --ui                       # Gradio frontend
"""

import asyncio
import argparse
import atexit
import logging
import sys
import io
import uuid
from pathlib import Path

# Experience Store — lightweight Monte-Carlo RL logging (best-effort, never crashes)
try:
    from core.experience import exp_store
    _EXPERIENCE_AVAILABLE = True
except Exception:
    _EXPERIENCE_AVAILABLE = False

# Monte Carlo Policy — reinforcement learning for orchestrator routing
try:
    from core.mc_learning import mc_policy
    _MC_POLICY_AVAILABLE = True
except Exception:
    _MC_POLICY_AVAILABLE = False


# ---- atexit safety net: flush RL data even if process is interrupted ----
def _emergency_flush():
    """Best-effort flush on any exit path (including SIGTERM)."""
    try:
        if _EXPERIENCE_AVAILABLE and exp_store._current_session_id is not None:
            exp_store.flush_session()
    except Exception:
        pass
    try:
        if _MC_POLICY_AVAILABLE and mc_policy._current_episode_id is not None:
            mc_policy.update_from_episode()
    except Exception:
        pass

atexit.register(_emergency_flush)

# Fix Windows console encoding for Unicode output
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

# Ensure directories exist BEFORE any handlers are created
Path("./logs").mkdir(exist_ok=True)
Path("./output").mkdir(exist_ok=True)
Path("./data/sensors").mkdir(parents=True, exist_ok=True)
Path("./data/biometric").mkdir(parents=True, exist_ok=True)
Path("./data/visual_fatigue").mkdir(parents=True, exist_ok=True)

# Setup logging (after dirs exist)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("logs/twinscientist.log", encoding="utf-8"),
    ],
)
logger = logging.getLogger("twinScientist")


async def run_research(question: str, domain: str, max_iter: int):
    """CLI 模式：运行研究循环（含蒙特卡洛 RL 生命周期管理）"""
    from config.settings import settings
    from core.graph import cognitive_graph
    from output.report_generator import ReportGenerator

    domain = domain or "环境—人体关联"
    settings.max_iterations = max_iter

    # --- Begin experience tracking for this research session ---
    _sid = None
    if _EXPERIENCE_AVAILABLE:
        try:
            _sid = exp_store.begin_session(domain=domain, query=question)
            if _sid:
                logger.info(f"[ExpStore] Session #{_sid} started for '{question[:60]}...'")
        except Exception:
            pass  # best-effort, never crash

    # --- Begin MC RL episode ---
    _mc_eid = None
    if _MC_POLICY_AVAILABLE:
        try:
            _mc_eid = mc_policy.begin_episode(domain=domain, query=question)
            if _mc_eid:
                logger.info(f"[MCPolicy] Episode #{_mc_eid} started")
        except Exception:
            pass  # best-effort, never crash

    initial_state = {
        "query": question,
        "domain": domain,
        "_max_iterations_": max_iter,
        "auto_confirm": True,  # CLI defaults to auto-confirm
    }

    print("=" * 70)
    print("  [twinScientist] AI Scientist")
    print(f"  领域: {initial_state['domain']}")
    print(f"  问题: {question}")
    if _MC_POLICY_AVAILABLE:
        stats = mc_policy.get_learning_stats()
        if stats.get("total_episodes", 0) > 0:
            print(f"  MC策略: {stats['total_episodes']} 个历史 episode, "
                  f"Q表大小={stats['q_table_size']}, ε={stats['epsilon']}")
    print("=" * 70)

    result = None
    try:
        thread_id = f"cli-session-{uuid.uuid4().hex[:8]}"
        logger.info(f"[CLI] Starting fresh session with thread_id={thread_id}")
        # LangGraph recursion_limit is overridden to 2000 (200 iterations × ~8 steps/iter)
        # Each iteration takes ~8 node steps, so use 200 * 10 as safety margin
        result = await cognitive_graph.ainvoke(
            initial_state,
            {"configurable": {"thread_id": thread_id}, "recursion_limit": 2000},
        )

        # Generate report — prefer final_report from graph (already has real data), else regenerate
        graph_report = result.get("final_report", "")
        generator = ReportGenerator()
        if graph_report and "理论可行性验证框架" not in graph_report:
            # Use the report generated by node_report_writing (has real causal inference results)
            report = graph_report
            path = await generator.save_report(report)
        else:
            logger.info("[CLI] No valid final_report from graph, generating from state...")
            report = await generator.generate_from_state(result)
            path = await generator.save_report(report)

        print("\n" + "=" * 70)
        print("  [SUCCESS] 研究完成！")
        print(f"  报告已保存: {path}")
        print("=" * 70)
        print("\n" + report[:2000])
        if len(report) > 2000:
            print(f"\n... (完整报告共 {len(report)} 字符，详见文件)")

        return result

    except Exception as e:
        logger.error(f"Research failed: {e}", exc_info=True)
        raise

    finally:
        # --- Flush experience store for this session (best-effort) ---
        if _sid and _EXPERIENCE_AVAILABLE:
            try:
                exp_store.flush_session()
                logger.info(f"[ExpStore] Session #{_sid} flushed")
            except Exception as e:
                logger.warning(f"[ExpStore] Flush failed: {e}")

        # --- Update MC RL policy from this episode (best-effort) ---
        if _mc_eid and _MC_POLICY_AVAILABLE:
            try:
                mc_policy.update_from_episode(final_state=result)
                stats = mc_policy.get_learning_stats()
                logger.info(
                    f"[MCPolicy] Episode #{_mc_eid} updated. "
                    f"Total episodes: {stats.get('total_episodes', 0)}, "
                    f"Q-table size: {stats.get('q_table_size', 0)}"
                )
            except Exception as e:
                logger.warning(f"[MCPolicy] Episode update failed: {e}")


def interactive_mode():
    """交互模式"""
    from data.organizer import organize_directory, UPLOAD_DIR

    print("[twinScientist] twinScientist — 自主科研智能体\n")
    print("=" * 60)
    print("  可用指令：")
    print("    [研究问题] <您的问题>   — 启动 AI 科研分析")
    print("    [数据上传]              — 自动整理放入 data/upload/ 的数据文件")
    print("    quit / exit / q         — 退出")
    print("=" * 60 + "\n")

    while True:
        raw = input("twinScientist > ").strip()
        if not raw:
            continue

        # Check for data upload command
        if raw.lower().startswith("[数据上传]") or raw.lower() == "upload":
            print("\n[data-upload] 正在扫描 data/upload/ 目录...")
            results = organize_directory(verbose=True)
            if results and all(r["skipped"] for r in results):
                print("\n[data-upload] 所有文件均无法识别类型。")
                print("        请确保 CSV 第一行为列名，包含相关指标（如 T、CO2、ppg、心率等）。")
            elif not results:
                print(f"\n[data-upload] data/upload/ 为空，请将数据文件放入 {UPLOAD_DIR} 后重试。\n")
            else:
                moved = sum(1 for r in results if r["moved"])
                print(f"\n[data-upload] ✅ {moved} 个文件已分类到对应数据目录，可开始研究了！\n")
            continue

        if raw.lower() in ("quit", "exit", "q"):
            print("再见！")
            break

        # Research question mode
        question = raw
        domain = input("学科领域 [默认: 环境—人体关联]: ").strip() or "环境—人体关联"
        max_iter = int(input("最大迭代次数 [默认: 200]: ") or "200")

        print()
        try:
            asyncio.run(run_research(question, domain, max_iter))
        except KeyboardInterrupt:
            print("\n中断。")
        except Exception as e:
            print(f"ERROR: {e}")
        print()


def ui_mode():
    """启动 Gradio Web UI"""
    from ui.app import create_demo
    demo = create_demo()
    demo.launch(server_name="127.0.0.1", server_port=7860)
    print("Web UI 已启动: http://127.0.0.1:7860")


def main():
    parser = argparse.ArgumentParser(description="twinScientist — AI Scientist CLI")
    parser.add_argument("--question", "-q", type=str, help="研究问题")
    parser.add_argument("--domain", "-d", type=str, help="学科领域")
    parser.add_argument("--iterations", "-i", type=int, default=200, help="最大迭代次数（最多200轮）")
    parser.add_argument("--ui", action="store_true", help="启动 Gradio Web UI")

    args = parser.parse_args()

    if args.ui:
        ui_mode()
    elif args.question:
        asyncio.run(run_research(args.question, args.domain, args.iterations))
    else:
        interactive_mode()


if __name__ == "__main__":
    main()
