"""
twinScientist CLI Entry Point

Usage:
    python -m main                          # Interactive mode
    python -m main --question "问题"          # CLI mode
    python -m main --ui                       # Gradio frontend
"""

import asyncio
import argparse
import logging
import sys
import io
import uuid
from pathlib import Path

# Fix Windows console encoding for Unicode output
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

# Ensure directories exist BEFORE any handlers are created
Path("./logs").mkdir(exist_ok=True)
Path("./output").mkdir(exist_ok=True)
Path("./data/sensors").mkdir(parents=True, exist_ok=True)
Path("./data/biometric").mkdir(parents=True, exist_ok=True)
Path("./data/visual_fatigue").mkdir(parents=True, exist_ok=True)

# Setup logging (after dirs exist)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("logs/twinscientist.log", encoding="utf-8"),
    ],
)
logger = logging.getLogger("twinScientist")


async def run_research(question: str, domain: str, max_iter: int):
    """CLI 模式：运行研究循环"""
    from config.settings import settings
    from core.graph import cognitive_graph
    from output.report_generator import ReportGenerator

    settings.max_iterations = max_iter

    initial_state = {
        "query": question,
        "domain": domain or "环境—人体关联",
        "_max_iterations_": max_iter,
        "auto_confirm": True,  # CLI defaults to auto-confirm
    }

    print("=" * 70)
    print("  [twinScientist] AI Scientist")
    print(f"  领域: {initial_state['domain']}")
    print(f"  问题: {question}")
    print("=" * 70)

    try:
        thread_id = f"cli-session-{uuid.uuid4().hex[:8]}"
        logger.info(f"[CLI] Starting fresh session with thread_id={thread_id}")
        result = await cognitive_graph.ainvoke(
            initial_state,
            {"configurable": {"thread_id": thread_id}},
        )

        # Generate report — prefer final_report from graph (already has real data), else regenerate
        graph_report = result.get("final_report", "")
        generator = ReportGenerator()
        if graph_report and "理论可行性验证框架" not in graph_report:
            # Use the report generated by node_report_writing (has real causal inference results)
            report = graph_report
            path = await generator.save_report(report)
        else:
            logger.info("[CLI] No valid final_report from graph, generating from state...")
            report = await generator.generate_from_state(result)
            path = await generator.save_report(report)

        print("\n" + "=" * 70)
        print("  [SUCCESS] 研究完成！")
        print(f"  报告已保存: {path}")
        print("=" * 70)
        print("\n" + report[:2000])
        if len(report) > 2000:
            print(f"\n... (完整报告共 {len(report)} 字符，详见文件)")

        return result

    except Exception as e:
        logger.error(f"Research failed: {e}", exc_info=True)
        raise


def interactive_mode():
    """交互模式"""
    print("[twinScientist] twinScientist — 自主科研智能体\n")
    print("请输入你的研究问题，或键入 'quit' 退出。\n")

    while True:
        question = input("[研究问题] 研究问题: ").strip()
        if not question:
            continue
        if question.lower() in ("quit", "exit", "q"):
            print("再见！")
            break

        domain = input("学科领域 [默认: 环境—人体关联]: ").strip() or "环境—人体关联"
        max_iter = int(input("最大迭代次数 [默认: 10]: ") or "10")

        print()
        try:
            asyncio.run(run_research(question, domain, max_iter))
        except KeyboardInterrupt:
            print("\n中断。")
        except Exception as e:
            print(f"ERROR: {e}")
        print()


def ui_mode():
    """启动 Gradio Web UI"""
    from ui.app import create_demo
    demo = create_demo()
    demo.launch(server_name="127.0.0.1", server_port=7860)
    print("Web UI 已启动: http://127.0.0.1:7860")


def main():
    parser = argparse.ArgumentParser(description="twinScientist — AI Scientist CLI")
    parser.add_argument("--question", "-q", type=str, help="研究问题")
    parser.add_argument("--domain", "-d", type=str, help="学科领域")
    parser.add_argument("--iterations", "-i", type=int, default=10, help="最大迭代次数")
    parser.add_argument("--ui", action="store_true", help="启动 Gradio Web UI")

    args = parser.parse_args()

    if args.ui:
        ui_mode()
    elif args.question:
        asyncio.run(run_research(args.question, args.domain, args.iterations))
    else:
        interactive_mode()


if __name__ == "__main__":
    main()
