"""
Multi-language support for TwinScientist reports.

Supports English (en) and Chinese (zh). Add more languages by extending
the TRANSLATIONS dict with the same keys.

Usage:
    from core.language import get_text, LANGUAGES
    text = get_text("report_title", "en")
"""

from __future__ import annotations

# Available languages
LANGUAGES = {
    "en": "English",
    "zh": "中文",
}

TRANSLATIONS = {
    # Report section headers
    "report_title": {
        "en": "Scientific Hypothesis & Research Plan",
        "zh": "科学假设与研究计划",
    },
    "section_problem": {
        "en": "Problem Statement",
        "zh": "待研究问题",
    },
    "section_rationale": {
        "en": "Rationale",
        "zh": "解决思路",
    },
    "section_technical": {
        "en": "Technical Details",
        "zh": "技术手段",
    },
    "section_datasets": {
        "en": "Datasets",
        "zh": "数据集",
    },
    "section_title": {
        "en": "Paper Title",
        "zh": "论文标题",
    },
    "section_abstract": {
        "en": "Abstract",
        "zh": "摘要",
    },
    "section_methods": {
        "en": "Methods",
        "zh": "方法论",
    },
    "section_experiments": {
        "en": "Experiments",
        "zh": "实验设计",
    },
    "section_results": {
        "en": "Results",
        "zh": "实验结果",
    },
    "section_review": {
        "en": "Reviewer Feedback",
        "zh": "评审意见",
    },
    "section_references": {
        "en": "References",
        "zh": "参考文献",
    },
    "section_appendix": {
        "en": "Additional Information",
        "zh": "附加信息",
    },
    "section_n_of_1": {
        "en": "N-of-1 Individual Analysis",
        "zh": "N-of-1 个体化分析",
    },
    "section_data_quality": {
        "en": "Data Quality Overview",
        "zh": "数据质量概览",
    },
    "section_convergence": {
        "en": "Convergence Over Iterations",
        "zh": "收敛度变化",
    },
    "section_hypothesis_tree": {
        "en": "Hypothesis Tree",
        "zh": "假设树全景",
    },
    "section_evidence": {
        "en": "Evidence Chain Summary",
        "zh": "证据链汇总",
    },
    "section_causal_results": {
        "en": "Causal Inference Results",
        "zh": "因果推断结果",
    },
    "section_evidence_timeline": {
        "en": "Evidence Timeline",
        "zh": "证据时间线",
    },

    # Status messages
    "iteration_status_ok": {
        "en": "Iterations completed: {n} round(s)",
        "zh": "已执行迭代: {n} 轮",
    },
    "iteration_status_warn": {
        "en": "Reflection loop not executed (current round: {n}). Consider increasing iterations.",
        "zh": "反思循环未被执行 (当前: {n} 轮)。建议增加迭代轮次。",
    },
    "generated_by": {
        "en": "This report was auto-generated by TwinScientist AI Scientist",
        "zh": "本报告由 TwinScientist AI Scientist 系统自动生成",
    },
    "generation_time": {
        "en": "Generation time: {time}",
        "zh": "生成时间: {time}",
    },
    "iteration_info": {
        "en": "Iterations: {iter}/{max_iter} | Convergence: {conv:.0f}%",
        "zh": "迭代轮次: {iter}/{max_iter} | 收敛度: {conv:.0f}%",
    },
    "agent_info": {
        "en": "Agent: Qwen Series (Alibaba Cloud Bailian) | Orchestration: LangGraph",
        "zh": "Agent: Qwen系列 (阿里云百炼平台) | 编排: LangGraph",
    },

    # N-of-1 section
    "n_of_1_intro": {
        "en": (
            "N-of-1 research is TwinScientist's core differentiator. Traditional population "
            "studies mask individual differences, while N-of-1 methods analyze the same "
            "individual's physiological responses across different environmental conditions, "
            "enabling truly personalized environment-health discovery."
        ),
        "zh": (
            "N-of-1 研究是 TwinScientist 的核心差异化能力。传统群体研究掩盖了个体差异，"
            "而 N-of-1 方法通过分析同一个体在不同环境条件下的生理响应，"
            "实现真正个性化的环境—健康关联发现。"
        ),
    },
    "n_of_1_highlight": {
        "en": (
            "Competition highlight: N-of-1 + LLM + IoT sensors is a frontier direction "
            "highlighted by Nature Digital Medicine and The Lancet Digital Health in 2025. "
            "TwinScientist is currently the only open-source system combining this paradigm "
            "with an autonomous AI Scientist pipeline."
        ),
        "zh": (
            "比赛亮点: N-of-1 + LLM + IoT 传感器是 2025 年 Nature Digital Medicine 和 "
            "The Lancet Digital Health 关注的前沿方向。TwinScientist 是目前唯一将此范式 "
            "与 AI Scientist 自主科研流程结合的开源系统。"
        ),
    },

    # Data
    "data_source_label": {
        "en": "Actual Data Used",
        "zh": "实际使用的数据",
    },
    "data_target_label": {
        "en": "Target Data Characteristics",
        "zh": "验证实验拟采集数据特征",
    },
    "data_file_type_env": {
        "en": "Environmental Sensor",
        "zh": "环境传感器",
    },
    "data_file_type_bio": {
        "en": "Biometric",
        "zh": "生物特征",
    },

    # Baseline comparison
    "baseline_pearson": {
        "en": "Pearson correlation — linear association detection",
        "zh": "Pearson 相关 — 线性关联检测",
    },
    "baseline_spearman": {
        "en": "Spearman rank — monotonic association",
        "zh": "Spearman 秩相关 — 单调关联检测",
    },
    "baseline_causal": {
        "en": "Causal inference — direction + significance",
        "zh": "因果推断 — 方向性 + 统计显著性",
    },
    "baseline_conclusion": {
        "en": (
            "Conclusion: Causal inference methods determine causal direction and provide "
            "statistical significance tests, unlike simple correlation. "
            "The {method} method achieved evidence strength of {strength:.3f}, "
            "{status}."
        ),
        "zh": (
            "结论: 因果推断方法相比简单相关性分析，能确定因果方向并提供统计显著性检验。"
            "本研究中 {method} 方法的证据强度为 {strength:.3f}，{status}。"
        ),
    },
    "baseline_status_strong": {
        "en": "meeting the strong evidence threshold",
        "zh": "达到强证据标准",
    },
    "baseline_status_weak": {
        "en": "suggesting further validation is recommended",
        "zh": "建议进一步验证",
    },

    # Evidence strength
    "evidence_strong": {
        "en": "strong",
        "zh": "强",
    },
    "evidence_moderate": {
        "en": "moderate",
        "zh": "中等",
    },
    "evidence_weak": {
        "en": "weak",
        "zh": "弱",
    },

    # Educational annotations
    "edu_ethics_check": {
        "en": (
            "Ethics review is the first line of defense for AI Scientist. "
            "The system checks research questions for high-risk content (weaponization, "
            "privacy violations, human subject ethics violations), ensuring all research "
            "stays within safe boundaries."
        ),
        "zh": (
            "伦理审查是 AI Scientist 的第一道防线。系统检查研究问题是否涉及高风险内容"
            "（如武器化、隐私侵犯、人体实验伦理违规），确保所有研究在安全边界内进行。"
        ),
    },
    "edu_literature_review": {
        "en": (
            "Literature review is the starting point of scientific research. The system "
            "searches Crossref + arXiv databases in parallel, extracts structured scientific "
            "facts via LLM, and cross-validates them with CitationValidator."
        ),
        "zh": (
            "文献调研是科学研究的起点。系统并行搜索 Crossref + arXiv 数据库获取真实论文，"
            "然后由 LLM 提取结构化科学事实并通过 CitationValidator 交叉验证。"
        ),
    },
    "edu_hypothesis_gen": {
        "en": (
            "Hypothesis generation uses a triple-path reasoning engine: inductive reasoning "
            "summarizes trends from facts, deductive reasoning derives from domain rules, "
            "and abductive reasoning infers the most likely explanation for anomalies."
        ),
        "zh": (
            "假设生成采用三路推理引擎：归纳推理从已有事实中总结趋势，"
            "演绎推理从领域专家规则库向下推导，溯因推理从反直觉现象反推最可能解释。"
        ),
    },
    "edu_data_analysis": {
        "en": (
            "The data analysis phase uses causal inference rather than simple correlation. "
            "The system automatically selects the optimal method: Granger causality for "
            "time-series, CCM for nonlinear dynamics, and counterfactual for intervention effects."
        ),
        "zh": (
            "数据分析阶段使用因果推断而非简单相关性分析。"
            "系统自动选择最优方法：Granger 因果检验判断时序因果关系，"
            "CCM 收敛交叉映射检测非线性动态耦合，反事实推演估计干预效应。"
        ),
    },
    "edu_reviewer": {
        "en": (
            "Five-dimension peer review scores novelty, feasibility, methodology, evidence "
            "strength, and impact. Score >= 60 passes with Bayesian posterior update; "
            "< 60 requires revision. This ensures only rigorously reviewed hypotheses advance."
        ),
        "zh": (
            "五维评审从新颖性、可行性、方法论、证据强度、影响力五个维度打分，"
            "模拟学术同行评议。得分>=60通过并更新 Bayesian 后验概率，"
            "<60 打回修改。这种机制确保只有经过严格审查的假设才能进入下一轮。"
        ),
    },
    "edu_debate": {
        "en": (
            "Multi-Agent Debate: Pro Agent defends the hypothesis with evidence and logic; "
            "Con Agent identifies flaws, alternative explanations, and uncontrolled confounders; "
            "Judge Agent delivers an impartial verdict. This adversarial mechanism mirrors "
            "the peer review process in the scientific community."
        ),
        "zh": (
            "智能体思辨 — 多 Agent 辩论: Pro Agent 为假设提供证据支撑和逻辑论证；"
            "Con Agent 寻找漏洞、替代解释和未控制混杂因子；"
            "Judge Agent 综合双方论据做出公正裁决。"
            "这种对抗性辩论机制模拟了科学共同体中的同行评议过程。"
        ),
    },
    "edu_hitl": {
        "en": (
            "Human-in-the-Loop is a core design principle of AI Scientist. "
            "After the report is generated, users can question conclusions, request "
            "re-analysis, or explore alternative explanations. This ensures AI is an "
            "assistant to scientists, not a replacement — final decisions remain human."
        ),
        "zh": (
            "人在回路是 AI Scientist 的核心设计原则。"
            "研究报告生成后，用户可以质疑结论、要求重新分析、或探索替代解释。"
            "这确保了 AI 是科学家的助手而非替代品，最终决策权始终在人类手中。"
        ),
    },
}


def get_text(key: str, lang: str = "en", **kwargs) -> str:
    """
    Get translated text for a given key and language.

    Args:
        key: Translation key (e.g., "report_title")
        lang: Language code ("en" or "zh")
        **kwargs: Format arguments for the translation string

    Returns:
        Translated string in the requested language
    """
    translations = TRANSLATIONS.get(key, {})
    text = translations.get(lang) or translations.get("en", key)
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, ValueError):
            pass
    return text


def get_language_label(lang: str) -> str:
    """Get the display name for a language code."""
    return LANGUAGES.get(lang, lang)